---
title: "Test of closed cartesian objects"
output: html_notebook
---

```{r}
library(devtools)
library(ggplot2)
library(dplyr)
library(gridExtra)

source('coord_closed_cart.R')
theme_set(theme_bw() + theme(panel.border=element_blank(), axis.line=element_line()))
options(stringsAsFactors=FALSE)
```


```{r data1}
dat1 <- data.frame(
   gp = factor(rep(letters[1:3], each = 10)),
   y = rnorm(30),
   cl = sample.int(3, 30, replace=TRUE),
   cl2 = sample(c('a','b','c'), 30, replace=TRUE)
)
```

## Testing simple closed sets

### Ordinary cartesian coordinate
```{r, fig.height=12, fig.width=12}
test.plot <- function(h, v) ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_cart(horizontal = h, vertical=v) + 
  labs(title=sprintf('Horizontal: %s, Vertical: %s', h, v)) + theme(axis.title=element_blank(), plot.title=element_text(size=rel(1)))

plots <- expand.grid(h=c('left','right','both','none'), v=c('top','bottom','both','none'),  stringsAsFactors = FALSE) %>%
  with(mapply(test.plot, h=h, v=v, SIMPLIFY=FALSE))
grid.arrange(grobs=plots, ncol=4)

```

### Flipped cartesian coordinate
```{r, fig.height=12, fig.width=12}
test.plot <- function(h, v) ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_flipped(horizontal = h, vertical=v) + 
  labs(title=sprintf('Horizontal: %s, Vertical: %s', h, v)) + theme(axis.title=element_blank(), plot.title=element_text(size=rel(1)))

plots <- expand.grid(h=c('left','right','both','none'), v=c('top','bottom','both','none'),  stringsAsFactors = FALSE) %>%
  with(mapply(test.plot, h=h, v=v, SIMPLIFY=FALSE))
grid.arrange(grobs=plots, ncol=4)

```


## Facet wrap?

```{r}
ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_flipped(horizontal = 'left', vertical='none') + 
  theme(axis.title=element_blank(), plot.title=element_text(size=rel(1))) +
  facet_wrap(~cl, ncol=2)

```

## Facet grid?

```{r}
ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_flipped(horizontal = 'left', vertical='none') + 
  theme(axis.title=element_blank(), plot.title=element_text(size=rel(1))) +
  facet_grid(.~cl)
```

```{r}
ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_flipped(horizontal = 'left', vertical='none') + 
  theme(axis.title=element_blank(), plot.title=element_text(size=rel(1))) +
  facet_grid(cl2~cl)
```

```{r}
ggplot(dat1, aes(gp, y)) + geom_point() + coord_closed_flipped(horizontal = 'left', vertical='none') + 
  theme(axis.title=element_blank(), plot.title=element_text(size=rel(1))) +
  facet_grid(cl2 ~ .)
```